name: 'Delete All Azure Resources'

on:
  workflow_dispatch:  # Manual trigger

jobs:
  delete:
    name: 'Delete Azure Resources via Bash'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure and Delete All Resource Groups
        run: |
          az login --service-principal \
            --username "$ARM_CLIENT_ID" \
            --password "$ARM_CLIENT_SECRET" \
            --tenant "$ARM_TENANT_ID"

          az account set --subscription "$ARM_SUBSCRIPTION_ID"

          RESOURCE_GROUPS=$(az group list --query "[].name" -o tsv)

          for RG in $RESOURCE_GROUPS; do
            echo "Deleting resource group: $RG"
            az group delete --name "$RG" --yes --no-wait
          done

          echo "All resource groups scheduled for deletion."
